name: "buildiso"
on:
  push:
    tags:
      - 'iso-v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install Nix
      uses: cachix/install-nix-action@v18
      with:
        nix_path: nixpkgs=channel:nixos-unstable

    - name: Install Cachix
      run: |
        nix-env -iA cachix -f https://cachix.org/api/v1/install
        cachix use nix-community


    - name: Get Files
      run: |
        curl -O https://github.com/dongdigua/dongdigua.github.io/raw/main/org/internet_collections.org
        curl https://people.centos.org/areguera/backgrounds/c9/default/standard/hue-0.png -o centos9-motif.png

    - name: Fallback Patch
      run: |
        ./fallbacks/rofi.sh
        ./fallbacks/vim.sh
        ./fallbacks/emacs.sh
        patch -p0 < fallbacks/waybar.patch waybar/config

    - name: Pre Process
      run: |
        sudo apt install gpp
        ./gpp.sh configuration.nix > iso.nix
        cp sway/config sway/config.orig
        ./gpp.sh sway/config.orig  > sway/config

    - name: Build ISO
      run: |
        nix run github:nix-community/nixos-generators -- -f iso -c iso.nix -o output
        df -h

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "output/iso/nixos.iso"
